name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
          sed -i 's/\r//' ~/.ssh/ec2_key   # remove Windows line endings
          chmod 600 ~/.ssh/ec2_key
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy app to EC2
        run: |
          ssh -i ~/.ssh/ec2_key -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            set -e  # Exit immediately if any command fails

            # Ensure directory exists
            mkdir -p ~/simple-node-cicd-app
            cd ~/simple-node-cicd-app

            # If repo not cloned yet, clone it
            if [ ! -d .git ]; then
              git clone https://github.com/${{ github.repository }} .
            else
              git fetch origin main
              git reset --hard origin/main
            fi

            # Install Node + PM2 if missing
            if ! command -v npm >/dev/null 2>&1; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            sudo npm install -g pm2

            # Install dependencies
            npm install

            # Restart the app using PM2
            pm2 delete node-app || true
            pm2 start server.js --name node-app
            pm2 save
          EOF
